# Generated by Django 5.1.3 on 2024-11-12 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_country_userprofile_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='birth_date',
            new_name='birthdate',
        ),
    ]
