# Generated by Django 5.1.3 on 2024-11-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='cover_picture',
            new_name='cover_image',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='language',
            new_name='native_language',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_picture',
            new_name='profile_image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
    ]
