# Generated by Django 5.1.3 on 2024-11-12 17:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=255)),
                ('card_holder', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[0-9]{16}$')])),
                ('bank_name', models.CharField(max_length=255)),
                ('valid_date', models.DateField()),
                ('color', models.CharField(choices=[('#FF5733', 'Orange'), ('#33FFFC', 'Blue'), ('#DAF7A6', 'Green'), ('#581845', 'Purple')], default='#FF5733', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
