# Generated by Django 5.1.3 on 2024-11-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_coin_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='balance',
            field=models.FloatField(default=20000),
        ),
    ]
