# Generated by Django 5.1.3 on 2024-11-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_settings', '0002_alter_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
